#!/usr/bin/env python

"""Convert the question and answer files to the Annotation Assist format."""

import argparse

import pandas

RESPONSE_MARKUP = "responseMarkup"
ID = "id"
ANSWER = "Answer"
ANSWER_ID = "AnswerId"
QUESTION = "Question"
CONFIDENCE = "Confidence"


def convert_corpus(corpus_file, n):
    corpus = pandas.read_csv(corpus_file, encoding="utf-8", nrows=n)
    corpus.rename(columns={"id": "pauId", "responseMarkup": "text", "sourceName": "fileName"}, inplace=True)
    corpus["splitPauTitle"] = corpus["title"].apply(lambda title: title.split(":"))
    corpus.drop(["answeredByPau", "normalizedScore", "sourceDocUrl", "score", "title"], axis="columns", inplace=True)
    return corpus.to_json(orient="records")


def convert_qa(corpus_file, system_files):
    corpus = pandas.read_csv(corpus_file, encoding="utf-8")
    systems = [pandas.read_csv(system_file, encoding="utf-8") for system_file in system_files]
    # Get a mapping of answer Ids to answers from the corpus.
    corpus = corpus[[RESPONSE_MARKUP, ID]]
    corpus.rename(columns={RESPONSE_MARKUP: ANSWER, ID: ANSWER_ID}, inplace=True)
    systems = [pandas.merge(system, corpus, on=ANSWER_ID) for system in systems]
    systems = pandas.concat(systems).drop_duplicates().set_index(QUESTION)
    systems.rename(columns={QUESTION: "QuestionText", ANSWER: "TopAnswerText", CONFIDENCE: "TopAnswerConfidence"},
                   inplace=True)
    # Add a dummy date time because the Annotation Assist README says that this column is required.
    systems["DateTime"] = "06052015:061049:UTC"
    return systems


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("corpus", type=argparse.FileType(), help="corpus file to convert")
    parser.add_argument("systems", type=argparse.FileType(), nargs="+",
                        help="Results file generated by answer_questions.py")
    args = parser.parse_args()

    print(convert_qa(args.corpus, args.systems).to_csv(encoding="utf-8"))
