#!/usr/bin/env python

"""Join the results files generated by answer_questions.py into a single CSV."""

import argparse
import os

import pandas


def collate_qa_systems(results):
    fs = []
    for label, f in results:
        f = f.set_index("Question")
        f.columns = pandas.MultiIndex.from_tuples([(label, c) for c in f.columns])
        fs.append(f)
    return reduce(lambda m, f: m.join(f), fs)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("results", type=argparse.FileType(), nargs="+", help="Results files")
    args = parser.parse_args()
    results = [(os.path.basename(result.name), pandas.read_csv(result, encoding="utf-8")) for result in args.results]
    print(collate_qa_systems(results).to_csv(encoding="utf-8"))
