#!/usr/bin/env python

"""Extract a test set from the augmented WEA logs generated by add_answer_ids_to_wea_logs.py"""
import argparse
import logging

import pandas

logger = logging.getLogger(__name__)

QUESTION = "Question"
QUESTION_TEXT = "QuestionText"
ANSWER_ID = "AnswerId"


def create_test_set(questions_data_file, answer_id_required):
    test_set = pandas.read_csv(questions_data_file, usecols=[QUESTION_TEXT, ANSWER_ID], encoding="utf-8")
    logger.info("%d questions" % len(test_set))
    test_set.rename(columns={QUESTION_TEXT: QUESTION}, inplace=True)
    # Optionally only retain questions that were mapped to an answer ID.
    if answer_id_required:
        test_set = test_set[test_set[ANSWER_ID].notnull()]
    # Drop duplicate questions.
    test_set.drop_duplicates(QUESTION, inplace=True)
    logger.info("%d unique questions" % len(test_set))
    test_set.sort(QUESTION, inplace=True)
    return test_set[[QUESTION]]


def configure_logger(level, format):
    logger.setLevel(level)
    h = logging.StreamHandler()
    h.setFormatter(logging.Formatter(format))
    logger.addHandler(h)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("wea_logs", metavar="wea", type=argparse.FileType(), help="WEA logs with answer ID column")
    parser.add_argument("--answer-id-required", action="store_true", default=False,
                        help="Only retain questions that have an answer id")
    parser.add_argument('--log', type=str, default="ERROR", help="logging level")
    args = parser.parse_args()

    configure_logger(args.log.upper(), "%(asctime)-15s %(message)s")
    questions = create_test_set(args.wea_logs, args.answer_id_required)
    print(questions.to_csv(encoding="utf-8", index=False))
