"""
Generate and optionally draw precision and ROC curves.
"""
from themis import CsvFileType


def curves_command(subparsers):
    curves_parser = subparsers.add_parser("analyze", help="analyze judgments of Q&A performance")
    curves_parser.add_argument("type", choices=["roc", "precision"], help="type of curve to create")
    curves_parser.add_argument("answers", type=CsvFileType(), nargs="+",
                               help="answers generated by one of the 'qa' commands")
    curves_parser.add_argument("judgments", type=CsvFileType(),
                               help="Q&A pair judgments generated by the 'judge interpret' command")
    curves_parser.add_argument("--label", nargs="+", help="names of the Q&A sytsems")
    curves_parser.add_argument("--output", default=".", help="output directory")
    curves_parser.set_defaults(func=curves_handler)


def curves_handler(args):
    pass
