"""
Generate and optionally draw precision and ROC curves.
"""
import os

import pandas

from themis import CsvFileType, to_csv
from themis.annotate import JudgmentFileType
from themis.curves import generate_curves, plot_curves
from themis.xmgr import FrequencyFileType


def curves_command(parser, subparsers):
    curves_parser = subparsers.add_parser("curves", help="generate performance curves")
    curves_parser.add_argument("type", choices=["roc", "precision"], help="type of curve to create")
    curves_parser.add_argument("answers", type=CsvFileType(), nargs="+",
                               help="answers generated by one of the 'qa' commands")
    curves_parser.add_argument("--labels", nargs="+", help="names of the Q&A systems")
    curves_parser.add_argument("--frequency", required=True, type=FrequencyFileType(),
                               help="question frequency generated by the 'xmgr frequency' command")
    curves_parser.add_argument("--judgments", required=True, nargs="+", type=JudgmentFileType(),
                               help="Q&A pair judgments generated by the 'judge interpret' command")
    curves_parser.add_argument("--output", default=".", help="output directory")
    curves_parser.add_argument("--draw", action="store_true", help="draw plots")
    curves_parser.set_defaults(func=CurvesHandlerClosure(parser))


def curves_handler(parser, args):
    if args.labels is None:
        args.labels = [answers.filename for answers in args.answers]
    elif not len(args.answers) == len(args.labels):
        parser.print_usage()
        parser.error("There must be a name for each plot.")
    labeled_qa_pairs = zip(args.labels, args.answers)
    judgments = pandas.concat(args.judgments)
    curves = generate_curves(args.type, labeled_qa_pairs, judgments, args.frequency)
    # Write curves data.
    for label, data in curves.items():
        filename = os.path.join(args.output, "%s.%s.csv" % (args.type, label))
        to_csv(filename, data)
    # Optionally draw plot.
    if args.draw:
        plot_curves(curves)


class CurvesHandlerClosure(object):
    def __init__(self, parser):
        self.parser = parser

    def __call__(self, args):
        curves_handler(self.parser, args)
