"""
Get answers to questions from various Q&A systems.

WEA
    Extract answer from usage logs.

Solr
    Lookup answers from a Solr database using questions as queries.

NLC
    Train an NLC model to answer questions using the truth file downloaded from XMGR.
    1. train
    2. use
    3. list
    4. status
    5. delete
"""
import argparse

from themis import CsvFileType, ANSWER, ANSWER_ID
from themis.wea import WeaLogFileType


def qa_command(subparsers):
    qa_shared_arguments = argparse.ArgumentParser(add_help=False)
    qa_shared_arguments.add_argument("questions", type=CsvFileType(),
                                     help="question set generated by the 'xmgr questions' command")
    qa_shared_arguments.add_argument("output", type=str, help="output filename")

    parser = subparsers.add_parser("qa", help="answer questions with Q&A systems")
    subparsers = parser.add_subparsers(title="Q&A", description="the various Q&A systems", help="Q&A systems")
    # Extract answers from the usage log.
    qa_wea = subparsers.add_parser("wea", parents=[qa_shared_arguments], help="extract WEA answers from usage log")
    qa_wea.add_argument("usage_log", type=WeaLogFileType(), help="QuestionsData.csv usage log file from XMGR")
    qa_wea.set_defaults(func=wea_subcommand)
    # Query answers from a Solr database.
    qa_solr = subparsers.add_parser("solr", parents=[qa_shared_arguments], help="query answers from a Solr database")
    qa_solr.add_argument("url", type=str, help="solr URL")
    qa_solr.set_defaults(func=solr_subcommand)
    # Manage an NLC model.
    nlc_shared_arguments = argparse.ArgumentParser(add_help=False)
    nlc_shared_arguments.add_argument("url", help="NLC url")
    nlc_shared_arguments.add_argument("username", help="NLC username")
    nlc_shared_arguments.add_argument("password", help="NLC password")

    nlc_parser = subparsers.add_parser("nlc", help="answer questions with NLC")
    nlc_subparsers = nlc_parser.add_subparsers(title="Natural Language Classifier",
                                               description="train, use, and manage NLC models", help="NLC actions")
    # Train NLC model.
    nlc_train = nlc_subparsers.add_parser("train", parents=[nlc_shared_arguments], help="train an NLC model")
    nlc_train.add_argument("truth", type=CsvFileType(), help="truth file created by the 'xmgr truth' command")
    nlc_train.add_argument("name", help="classifier name")
    nlc_train.set_defaults(func=nlc_train_handler)
    # Use an NLC model.
    nlc_use = nlc_subparsers.add_parser("use", parents=[nlc_shared_arguments, qa_shared_arguments],
                                        help="use NLC model")
    nlc_use.add_argument("classifier", help="classifier id")
    nlc_use.add_argument("corpus", type=CsvFileType([ANSWER, ANSWER_ID]),
                         help="corpus file created by the xmgr command")
    nlc_use.add_argument("--checkpoint-frequency", type=int, default=100,
                         help="how often to flush to a checkpoint file")
    nlc_use.set_defaults(func=nlc_use_handler)
    # List all NLC models.
    nlc_list = nlc_subparsers.add_parser("list", parents=[nlc_shared_arguments], help="list NLC models")
    nlc_list.set_defaults(func=nlc_list_handler)
    # Get status of NLC models.
    nlc_status = nlc_subparsers.add_parser("status", parents=[nlc_shared_arguments], help="status of NLC model")
    nlc_status.add_argument("classifiers", nargs="+", help="classifier ids")
    nlc_status.set_defaults(func=nlc_shared_arguments)
    # Delete NLC models.
    nlc_delete = nlc_subparsers.add_parser("delete", parents=[nlc_shared_arguments], help="delete an NLC model")
    nlc_delete.add_argument("classifiers", nargs="+", help="classifier ids")
    nlc_delete.set_defaults(func=nlc_delete_handler)


def wea_subcommand(args):
    pass


def solr_subcommand(args):
    pass


def nlc_train_handler(args):
    pass


def nlc_use_handler(args):
    pass


def nlc_list_handler(args):
    pass


def nlc_delete_handler(args):
    pass
